### ISSUE TITLE
DKIM: body hash mismatch when using HTML or symbols in appended disclaimer

### ISSUE THREAD

**Issue by zimnysbrain** [NethServer/dev#5904] opened 2019-11-07 18:59 UTC
**Steps to reproduce**

When try using html or symbols like # or ' etc in appended disclaimer body hash is changed by milter which creates issues when validate dkim

**Comment by gsanchietti** [comment] 2019-11-11 13:00
Could you please add a disclaimer example to reproduce the issue?

**Comment by federicoballarini** [comment] 2019-11-21 00:11
I can't reproduce the bug.
I added some special chars into disclaimer fields and enabled DKIM but all seems to works fine.

**Comment by gsanchietti** [comment] 2019-11-21 09:23
I'm closing the issue because we can't reproduce it.
@zimnysbrain fell free to reopen the issue with more info directly inside the forum https://community.nethserver.org.

**Closed** 2019-11-21 09:23 UTC
Labels: bug, invalid
