### ISSUE TITLE
bypass domains in wpad

### ISSUE THREAD

**Issue by q16marvin** [NethServer/dev#6380] opened 2020-12-30 13:17 UTC
with this change in template:

```
foreach ($db->get_all_by_prop('type' => 'bypass-dst')) {
        next if ($_->prop('status') eq 'disabled');
        my $h = $_->prop('Host') || $_->prop('Domains') || next;
        my $address = $fw->getAddress($h);
        $OUT .= "    // Bypass destination: ".$_->key.": $h\n";
        if ($h =~ /cidr/) {
            $c = NetAddr::IP->new($address);
            $OUT .= '    if (isInNet(host, "'.$c->addr().'","'.$c->mask().'"))';
            $OUT .= "\n        return \"DIRECT\";\n";
        } elsif ($h =~ /host-group/) {
            foreach my $h (split(/,/,$address)) {
            $OUT .= '    if (isInNet(host,"'.$h.'", "255.255.255.255"))';
            $OUT .= "\n        return \"DIRECT\";\n";
            }
        } elsif ($h =~ /host/) {
            $OUT .= '    if (isInNet(host,"'.$address.'", "255.255.255.255"))';
            $OUT .= "\n        return \"DIRECT\";\n";
        } elsif ($_->prop('Domains')) {
           @Domains = split(',', $h);
			foreach my $d(@Domains){
				$OUT .= '    if (dnsDomainIs(host,"'.$d.'"))';
				$OUT .= "\n        return \"DIRECT\";\n";
			}
        } else {
            next;
        }
        $OUT .= "\n";
    }
```

wpad also include bypass for Domains

**Comment by gsanchietti** [comment] 2021-01-04 08:12
Duplicate of #6379

**Closed** 2021-01-04 08:12 UTC
Labels: invalid
