### ISSUE TITLE
Set the members of administrators group

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5168] opened 2016-12-01 17:11 UTC
The actual UI hides the system "administrators" group. Even if it is removed from the blacklist and forcibly displayed we should improve the member elements handling to support the AD concept of "subgroups", where a group member can be a group itself. Also "Domain Admins" must be visible and its members modified, because it is a common practice in AD world.

As further enhancement, with local account providers, the UI must avoid checking an account existence with getpwent() or similar glibc-based calls, that relies on sssd caching mechanisms. Account existence must be tested directly on the local provider DB.

Also the Dashboard panel that counts the system users should reflect the number of users and groups listed by the "Users and groups" page.

Components:

- nethserver-sssd
- nethserver-dc
- nethserver-directory

See also:

- http://community.nethserver.org/t/can-not-create-administrators-group-on-ns7-rc2/5083
- http://community.nethserver.org/t/why-is-the-groups-blank-when-adding-users-to-a-domain/4830
- http://community.nethserver.org/t/need-to-share-on-the-defunct-admin-user/4630
- http://community.nethserver.org/t/grant-full-control-to-a-domain-group/4434
- http://community.nethserver.org/t/errors-adding-user-to-group/4948

**Comment by DavidePrincipi** [comment] 2016-12-09 11:38
**Test case1**

- Dashboard account panel is hidden if provider is _none_
- Dashboard account panel counters reflects the number of items under Users & groups page

**Test case 2**

If local account provider is AD:

- Group members can be groups, too
- Add/remove members to/from a group by selecting user or existing group
- Create/modify a user and add it to existing groups

**Test case 3**

If local account provider is LDAP:

- The _admin_ account is member of _administrators_
- Other users can be added/removed to/from _administrators_

**Test case 4**

If provider is remote AD, the _administrators_ group is listed under _Users and groups_ page. Other builtin AD groups are **not** listed.



In nethserver-testing:
nethserver-sssd-1.0.8-1.52.g6546f32.ns7.noarch.rpm
nethserver-dc-1.0.7-1.6.g7149ae2.ns7.x86_64.rpm
nethserver-directory-3.1.0-1.33.gdb300d6.ns7.noarch.rpm

**Comment by gsanchietti** [comment] 2016-12-13 09:04
All test cases have been verified.

**Comment by Indra6oc** [comment] 2016-12-15 13:39
Tried first case, unattended install in virtualbox, full update, updated nethserver-sssd to testing.
Going to https://nethserver.local:980/en-US/Account returns error : 

> [1] Call to a member function isReadOnly() on a non-object
> See the system log for details.

messages log : 

> Dec 15 14:35:19 nethserver httpd: [1] Call to a member function isReadOnly() on a non-object - File /usr/share/nethesis/NethServer/Module/Account/User/UserAdapter.php, line 59

**Comment by gsanchietti** [comment] 2016-12-15 14:04
Sorry @Indra6oc  but I can't reproduce it. These are my rpms from testing:

> nethserver-lsm-1.2.0-1.6.g4bb992e.ns7.noarch
> nethserver-base-3.0.11-1.11.ge1b9cb1.ns7.noarch
> nethserver-letsencrypt-1.1.2-1.3.g96baf09.ns7.noarch
> nethserver-httpd-admin-2.0.4-1.2.g0bd6b69.ns7.noarch
> nethserver-duc-1.4.0-1.1.g03606ff.ns7.noarch
> nethserver-sssd-1.0.8-1.86.g221ea64.ns7.noarch

**Comment by Indra6oc** [comment] 2016-12-15 14:56
Retrying with interactive install

**Comment by Indra6oc** [comment] 2016-12-15 15:56
these are the versions I had the error on, trying now with updating them from testing

> --> Running transaction check
> ---> Package nethserver-base.noarch 0:3.0.11-1.ns7 will be updated
> ---> Package nethserver-base.noarch 0:3.0.11-1.11.ge1b9cb1.ns7 will be an update
> ---> Package nethserver-duc.noarch 0:1.4.0-1.ns7 will be updated
> ---> Package nethserver-duc.noarch 0:1.4.0-1.1.g03606ff.ns7 will be an update
> ---> Package nethserver-httpd-admin.noarch 0:2.0.4-1.ns7 will be updated
> ---> Package nethserver-httpd-admin.noarch 0:2.0.4-1.2.g0bd6b69.ns7 will be an update
> ---> Package nethserver-letsencrypt.noarch 0:1.1.2-1.ns7 will be updated
> ---> Package nethserver-letsencrypt.noarch 0:1.1.2-1.4.gacf6376.ns7 will be an update
> ---> Package nethserver-lsm.noarch 0:1.2.0-1.ns7 will be updated
> ---> Package nethserver-lsm.noarch 0:1.2.0-1.6.g4bb992e.ns7 will be an update
> --> Finished Dependency Resolution

**Comment by Indra6oc** [comment] 2016-12-15 16:01
after update from testing all fine, more tomorrow.

**Comment by gsanchietti** [comment] 2016-12-15 17:02
Released in 7.3.1611/base:

- nethserver-directory-3.1.1-1.ns7.noarch.rpm
- nethserver-sssd-1.1.0-1.ns7.noarch.rpm
- nethserver-dc-1.1.0-1.ns7.x86_64.rpm

**Closed by gsanchietti** 2016-12-15 17:02 UTC
Labels: verified
