### ISSUE TITLE
Fail2ban: Error: database is locked

### ISSUE THREAD

**Issue by stephdl** [NethServer/dev#6252] opened 2020-08-13 13:19 UTC
**Steps to reproduce**

- Install nethserver-fail2ban
- each night at 23:45 we run a script to find the number of ban for the day
- We might have some email from the cron job with this content `Error: database is locked`, the subject is `Cron <root@web> /usr/libexec/nethserver/fail2ban-statistics`

**Expected behavior**

I expect that the sqlite database is not locked and available for our needs

**Actual behavior**

I suspect that we try to use the database at the same moment that  fail2ban is writing to the sqlite database to store a ban. Mayb fail2ban could have badly closed the sql transaction
 
**Components**

nethserver-fail2ban

----

tk @filippocarletti

**Comment by federicoballarini** [comment] 2020-08-13 19:33
Hi @stephdl, I think this is a duplicate of https://github.com/NethServer/dev/issues/6253. Can we close this? :)

**Comment by stephdl** [comment] 2020-08-14 11:56
my bad I saved two times because github got somthing strange....I assume yes

**Closed** 2020-08-14 11:57 UTC
Labels: bug
