### ISSUE TITLE
Z-Push provokes memory leak

### ISSUE THREAD

**Issue by nrauso** [NethServer/dev#6126] opened 2020-04-10 14:42 UTC
In particular scenarios (for example if it is used for mail sync) *Z-Push* needs to allocate a large amount of resources and this behavior leads to a memory leak: *PHP72* grows the resource consumption without releasing those already in use and the system goes out of resources and start to kill other processes, evoking `oom-killer`.

Some logs outputs:
```
=>>/var/opt/rh/rh-php72/log/php-fpm/www-error.log<==
[05-Apr-2020 07:49:10 Europe/Rome] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 25439416 bytes) in /usr/share/webtop/z-
push/vendor/z-push/z-push/src/backend/imap/mimePart.php on line 335
[05-Apr-2020 07:49:43 Europe/Rome] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 70881176 bytes) in /usr/share/webtop/z-
push/vendor/z-push/z-push/src/backend/imap/imap.php on line 1039
```
```
==>/var/log/z-push/server.log<==
05/04/2020 07:49:10 [46241] [FATAL] [user@example.org] Fatal error: /usr/share/webtop/z-push/vendor/z-push/z-push/src/backend/imap/mimePart.php:335 - Allowed memory size of 134217728 bytes exhausted (tried to allocate 25439416 bytes) (1)
05/04/2020 07:49:46 [58560] [FATAL] [user@example.org] Fatal error: /usr/share/webtop/z-push/vendor/z-push/z-push/src/backend/imap/imap.php:1039 - Allowed memory size of 134217728 bytes exhausted (tried to allocate 70881176 bytes) (1)
```
```
==>/var/log/z-push/server_error.log<==
05/04/2020 07:49:10 [46241] [FATAL] [user@example.org] Fatal error: /usr/share/webtop/z-push/vendor/z-push/z-push/src/backend/imap/mimePart.php:335 - Allowed memory size of 134217728 bytes exhausted (tried to allocate 25439416 bytes) (1)
05/04/2020 07:49:46 [58560] [FATAL] [user@example.org] Fatal error: /usr/share/webtop/z-push/vendor/z-push/z-push/src/backend/imap/imap.php:1039 - Allowed memory size of 134217728 bytes exhausted (tried to allocate 70881176 bytes) (1)
```

Increase PHP72 `memory_limit` seems to workaround the problem:

```
echo -e "memory_limit = 512M" > /etc/opt/rh/rh-php72/php.d/00-memory-limit.ini
systemctl restart rh-php72-php-fpm
```

**Components**

- nethserver-rh-php72-php-fpm-1.1.1-1.ns7.noarch
- webtop5-zpush-1.2.1-1.ns7.noarch

**Comment by gsanchietti** [comment] 2020-04-14 09:12
I didn't find any official documentation, but it seems the described behavior it's true: PHP doesn't always free memory when a "Allowed memory size " error occurs.

It's hard to determine the cause of the problem which could be in the z-push code or in PHP itself.
As mitigation, we could tune FPM configuration to both increase the memory limit or restart child processes more often. In my opinion, the proposed workaround could not be applied to the while FPM instance because it affects multiple web applications.

We could eventually implement a specific FPM instance for `webtop5-zpush` package (see [nextcloud implementation](https://github.com/NethServer/nethserver-nextcloud/blob/master/root/etc/opt/rh/rh-php72/php-fpm.d/000-nextcloud.conf) as an example).

But please note that mail synchronization using zpush is [not supported](https://docs.nethserver.org/en/v7/webtop5.html#synchronization-with-activesync-eas).

Some further reading:
- http://www.phpinternalsbook.com/php7/extensions_design/php_lifecycle.html
- https://stackoverflow.com/questions/12015569/fatal-error-out-of-memory-but-i-do-have-plenty-of-memory-php
- https://stackoverflow.com/questions/8440439/safely-catch-a-allowed-memory-size-exhausted-error-in-php

**Comment by Amygos** [comment] 2020-04-14 16:12
I did some research and seems a common problem with mail synchronization, it was also reported on Nethserver community https://community.nethserver.org/t/z-push-memory-exhausted/7233
The common proposed solution is to increase the memory limit.

In our case since z-push is used only form webtop5 i think that the correct solution will be to disable

**Comment by Amygos** [comment] 2020-04-14 16:25
I did some research and seems a common problem with mail synchronization, it was also reported on Nethserver community https://community.nethserver.org/t/z-push-memory-exhausted/7233
The common proposed solution is to increase the memory limit.

In our case since z-push is used only for webtop5 i think that one solution can be, if possible, to disable the mail synchronization.
Otherwise i am also in favor of create a  dedicated FPM instance for `webtop5-zpush`.

**Comment by gsanchietti** [comment] 2020-04-15 16:15
We are going to increase the limit for new NS 7.8 installations, but we are not going to fix zpush: mail synchronization is still not supported.

A new custom configuration of FPM should be implemented in the next WebTop release.

This is issue will be closed and **WONTFIX**.

**Closed by gsanchietti** 2020-04-15 16:15 UTC
Labels: bug
