### ISSUE TITLE
Lack of "asterisk" user and group installing asterisk13

### ISSUE THREAD

**Issue by alepolidori** [NethServer/dev#5122] opened 2016-10-06 08:32 UTC
`asterisk-sounds-core-en-ulaw-1.5-1.8.noarch` is installed as dependency of `asterisk13`.
The installation emits a long series of warning messages on console:

> ...
> warning: user asterisk does not exist - using root
> warning: group asterisk does not exist - using root
> ...

At the end of asterisk13 installation the user has been created:

```
[root@ns7beta2-1 ~]# grep asterisk /etc/passwd
asterisk:x:993:990::/home/asterisk:/bin/bash
```

**Comment by gsanchietti** [comment] 2016-10-17 09:03
This is and upstream bug related to #5065

**Comment by gsanchietti** [comment] 2016-10-24 07:06
This is a working patch, waiting for upstream (@xrobau) accept it: https://github.com/gsanchietti/asterisk-sounds/commit/6dc1c0277beefe33fe68f7b2780789d99def0d03
I wasn't able to build the RPM using mock (probably because the sRPM is too big).

Updated packages in testing:

- asterisk-sounds-core-en-alaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en_AU-alaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en_AU-ulaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en_AU-wideband-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en_GB-alaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en_GB-ulaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en_GB-wideband-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en-ulaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en-wideband-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-es-alaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-es-ulaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-es-wideband-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-fr-alaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-fr-ulaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-fr-wideband-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-it-alaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-it-ulaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-it-wideband-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-ja-alaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-ja-ulaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-ja-wideband-1.5-2.el7.centos.noarch.rpm

*Test case*
- Check the bug is not reproducbile

**Comment by xrobau** [comment] 2016-10-25 04:18
The asterisk-sounds RPM needs to Require: shadow-utils, which contains the 'useradd' command.  Otherwise it may run BEFORE that has been installed, and will crash the install.

**Comment by gsanchietti** [comment] 2016-10-25 07:46
You're right, I missed the dependency for `useradd`, but the scenario you're describing is very unlikely to happen (even the asterisk13 rpm lacks this dependency).
We shouldn't add the shadow-utils dependency, since there is almost no package in a CentOS 7 which requires it. You can test it with:
```
rpm -e --test shadow-utils
```

The preferred solution is to add these lines to the spec:
```
Requires(pre): %{_sbindir}/groupadd
Requires(pre): %{_sbindir}/useradd
```

What do you think @xrobau ? Should I add these lines to each asterisk-sounds sub-package?

Just a couple of SRPM references:
- http://vault.centos.org/7.2.1511/os/Source/SPackages/postfix-2.10.1-6.el7.src.rpm
- ftp://mirror.switch.ch/pool/4/mirror/fedora/linux/releases/22/Everything/source/SRPMS/a/asterisk-13.1.1-1.fc22.src.rpm

**Comment by xrobau** [comment] 2016-10-25 19:48
That's probably a better idea, yes.

**Comment by xrobau** [comment] 2016-10-26 06:10
FYI, I've pulled this and merged it (along with the requires(pre) for group/useradd.. I didn't know about that one, thanks for the tip!

**Comment by gsanchietti** [comment] 2016-10-27 09:32
Added useradd/groupadd dependency:
https://github.com/gsanchietti/asterisk-sounds/commit/122a09c83f4679f215b595462109e01534fb8c4b

Uploaded again in nethserver-testing:
- asterisk-sounds-core-en-alaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en_AU-alaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en_AU-ulaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en_AU-wideband-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en_GB-alaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en_GB-ulaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en_GB-wideband-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en-ulaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-en-wideband-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-es-alaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-es-ulaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-es-wideband-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-fr-alaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-fr-ulaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-fr-wideband-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-it-alaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-it-ulaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-it-wideband-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-ja-alaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-ja-ulaw-1.5-2.el7.centos.noarch.rpm
- asterisk-sounds-core-ja-wideband-1.5-2.el7.centos.noarch.rpm

We should get rid of these rpms as soon as upstream release the updated once.

**Comment by gsanchietti** [comment] 2016-11-29 14:04
Recompiled RPMs have been replaced with upstream ones:
asterisk-sounds-core-en-alaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-en_AU-alaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-en_AU-ulaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-en_AU-wideband-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-en_GB-alaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-en_GB-ulaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-en_GB-wideband-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-en-ulaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-en-wideband-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-es-alaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-es-ulaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-es-wideband-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-fr-alaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-fr-ulaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-fr-wideband-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-it-alaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-it-ulaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-it-wideband-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-ja-alaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-ja-ulaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-core-ja-wideband-1.5-2.sng7.noarch.rpm
asterisk-sounds-extra-en-alaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-extra-en-ulaw-1.5-2.sng7.noarch.rpm
asterisk-sounds-extra-en-wideband-1.5-2.sng7.noarch.rpm
asterisk-sounds-moh-opsound-alaw-2.03-1.1.noarch.rpm
asterisk-sounds-moh-opsound-sln-2.03-1.1.noarch.rpm

Closing the issue.

**Closed by gsanchietti** 2016-11-29 14:04 UTC
Labels: bug, testing
