### ISSUE TITLE
OpenVPN status incorrect displayed in services WEB-GUI

### ISSUE THREAD

**Issue by markVnl** [NethServer/dev#5022] opened 2016-02-15 17:46 UTC
don’t know if it’s related, found this in  journalctl:

esmith::event[4380]: Failed to start openvpn.service: Unit openvpn.service failed to load: No such file or directory.

VPN works just fine, I think somewhere  “@host-to-net” is missing in a systmctl status query

**Comment by markVnl** [comment] 2016-02-16 09:18
after sogo update (Software center):

```
Task completed with errors
Adjust service openvpn #51 (exit status 1)
failed
```

In journalctl:
`esmith::event[9461]: Failed to start openvpn.service: Unit openvpn.service failed to load: No such file or directory.`

**Comment by filippocarletti** [comment] 2016-02-16 09:27
I think that all operations on the system will report the openvpn service error until it will be fixed.
Could you please check that Enable roadwarrior server in OpenVPN is checked? I can't reproduce the issue.

**Comment by gsanchietti** [comment] 2016-02-16 11:39
The bug is reproducible launching the runlevel-adjust action:

> [root@nethtest1 events]# /etc/e-smith/events/actions/runlevel-adjust  myevent
> Failed to start openvpn.service: Unit openvpn.service failed to load: No such file or directory.

The reason is openvpn is a key of type service: it was left untouched to avoid changes to firewall configuration.

I would like to fix it inside the code which currently handle systemd services. /cc @DavidePrincipi

**Comment by DavidePrincipi** [comment] 2016-02-17 09:34
> I would like to fix it inside the code which currently handle systemd services

We could re-think the "runlevel-adjust" implementation from scratch. Now we have processes supervised by systemd and this command

    systemctl isolate

**Comment by DavidePrincipi** [comment] 2016-04-13 07:48
http://packages.nethesis.it/nethserver/7.2.1511/testing/x86_64/Packages/nethserver-openvpn-1.3.0-1.4.gad20687.ns7.noarch.rpm

**Closed** 2016-05-16 15:17 UTC
Labels: BUG, verified
