### ISSUE TITLE
Notify changes to NethServer::SSSD clients

### ISSUE THREAD

**Issue by DavidePrincipi** [NethServer/dev#5164] opened 2016-12-01 15:35 UTC
By now the nethserver-sssd-save event notifies NethServer::SSSD client applications with a system-adjust. 

This method is slow and invokes a lot of *-update events that could cause any kind of side effects.

We should replace the system-adjust with an action that finds what packages requires the notification and invoke their *-update events only.

**Comment by DavidePrincipi** [comment] 2016-12-02 09:47
**Test case**

- Install all/any of ejabberd, NextCloud, Roundcubemail, squid
- Run nethserver-sssd-save event

The -update events of dependant packages must be invoked.

In nethserver-testing:
nethserver-sssd-1.0.8-1.33.gab57573.ns7.noarch.rpm

**Comment by gsanchietti** [comment] 2016-12-02 15:27
Tested on a machine with ejabberd, freepbx and nextcloud installed.

Event launched manually:
```
Dec  2 16:18:01 test esmith::event[26101]: Event: nethserver-sssd-save
Dec  2 16:18:02 test esmith::event[26172]: Event: nethserver-ejabberd-update
Dec  2 16:18:03 test esmith::event[26172]: Event: nethserver-ejabberd-update SUCCESS
Dec  2 16:18:03 test esmith::event[26277]: Event: nethserver-freepbx-update
Dec  2 16:18:08 test esmith::event[26277]: Event: nethserver-freepbx-update SUCCESS
Dec  2 16:18:08 test esmith::event[26489]: Event: nethserver-nextcloud-update
Dec  2 16:18:12 test esmith::event[26489]: Event: nethserver-nextcloud-update SUCCESS
Dec  2 16:18:12 test esmith::event[26571]: Event: nethserver-sssd-update
Dec  2 16:18:12 test esmith::event[26571]: Event: nethserver-sssd-update SUCCESS
Dec  2 16:18:13 test esmith::event[26101]: Event: nethserver-sssd-save SUCCESS
```
Installed nethserver-directory:
```
Dec  2 16:19:26 test esmith::event[26694]: Event: nethserver-directory-update
Dec  2 16:19:29 test esmith::event[26740]: Event: nethserver-sssd-save
Dec  2 16:19:30 test esmith::event[26863]: Event: nethserver-directory-update
Dec  2 16:19:34 test esmith::event[26863]: Event: nethserver-directory-update SUCCESS
Dec  2 16:19:34 test esmith::event[26980]: Event: nethserver-ejabberd-update
Dec  2 16:19:35 test esmith::event[26980]: Event: nethserver-ejabberd-update SUCCESS
Dec  2 16:19:35 test esmith::event[27090]: Event: nethserver-freepbx-update
Dec  2 16:19:43 test esmith::event[27090]: Event: nethserver-freepbx-update SUCCESS
Dec  2 16:19:43 test esmith::event[27318]: Event: nethserver-nextcloud-update
Dec  2 16:19:52 test esmith::event[27318]: Event: nethserver-nextcloud-update SUCCESS
Dec  2 16:19:53 test esmith::event[27504]: Event: nethserver-sssd-update
Dec  2 16:19:53 test esmith::event[27504]: Event: nethserver-sssd-update SUCCESS
Dec  2 16:19:54 test esmith::event[26740]: Event: nethserver-sssd-save SUCCESS
Dec  2 16:19:55 test esmith::event[26694]: Event: nethserver-directory-update SUCCESS
```
Note: nethserver-directory-update is executed twice but without side effects

**Comment by gsanchietti** [comment] 2016-12-02 15:36
The issue is verified but I propose to reorder the actions inside `nethserver-directory-update` event:
- nethserver-directory-createadmins -> 50
- move nethserver-directory-password-policy -> 60
- nethserver-directory-sssd -> 90

**Comment by gsanchietti** [comment] 2016-12-15 17:02
Released in 7.3.1611/base:

- nethserver-sssd-1.1.0-1.ns7.noarch.rpm

**Closed by gsanchietti** 2016-12-15 17:02 UTC
Labels: verified
